
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: p2p-app-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  generators:
    - list:
        elements:
          - cluster: main
            url: 'https://kubernetes.default.svc'
            namespace: default
            patch: prod
  template:
    metadata:
      name: 'p2p-app-{{cluster}}-prod'
    spec:
      project: default
      source:
        repoURL: https://github.com/javiee/p2p
        path: p2p-app/charts
        targetRevision: p2p-exercise
        helm:
          valueFiles:
            - values.yaml
            - 'values-{{patch}}.yaml'
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
    