name: p2p app build

on:

  workflow_dispatch:
  push:
    branches:
      - p2p-exercise


env:
  GO_VERSION: 1.23.3
  PROJECT: p2p-app
  DOCKER_IMAGE: javiee/p2p-app
  DOCKER_TAG: latest
  DEVELOP_BRANCH: p2p-exercise

jobs:
  go-build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: off 
      CGO_ENABLED: 0 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        working-directory: ./p2p-app
        run: go build -o main main.go

      - name: Test with Go
        working-directory: ./p2p-app/tests
        run: |
            go test -v -json > report-${{ env.PROJECT }}.json
            cat report-${{ env.PROJECT }}.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: test-result
          path: ./p2p-app/tests/report-${{ env.PROJECT }}.json


  calculate-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Calculate Docker tag
      - name: Determine Docker Tag
        id: calculate-tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/${DEVELOP_BRANCH}" ]; then
            TAG_PREFIX=$(git rev-parse --short HEAD)
            echo "TAG=dev-$TAG_PREFIX" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "Unable to determine tag"
            exit 1
          fi
      - name: Print Docker Tag
        run: echo "Docker Tag: ${{ env.TAG }}"
  
  docker-publish:
    if: github.ref == 'refs/heads/p2p-exercise' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: ['go-build','calculate-tag']
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: javiee
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker build
        working-directory: ./p2p-app
        run: docker build -f docker/Dockerfile -t $DOCKER_IMAGE:${{ env.TAG }} .

      - name: Push Docker image
        working-directory: ./p2p-app
        run: docker push $DOCKER_IMAGE:${{ env.TAG }}

