name: p2p app build

on:

  workflow_dispatch:
  push:
    branches:
      - p2p-exercise


env:
  GO_VERSION: 1.23.3
  PROJECT: p2p-app
  DOCKER_IMAGE: javiee/p2p-app
  DOCKER_TAG: latest
  DEVELOP_BRANCH: develop

jobs:
  go-build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: off 
      CGO_ENABLED: 0 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        working-directory: ./p2p-app
        run: go build -o main main.go

      - name: Test with Go
        working-directory: ./p2p-app/tests
        run: |
            go test -v -json > report-${{ env.PROJECT }}.json
            cat report.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: test-result
          path: ./p2p-app/tests/report-${{ env.PROJECT }}.json

  calculate-tag:
    if: github.ref == 'refs/heads/p2p-exercise' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set version tah
        run: | 
            env
            set +x
            if [ "${{ github.ref }}" == "refs/heads/${DEVELOP_BRANCH}" ]; then
              RANDOM_TAG=$(uuidgen | cut -c1-8)
              echo "tag=dev-$RANDOM_TAG" >> $GITHUB_ENV
            elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
              echo "tag=latest" >> $GITHUB_ENV
            fi
            echo $tag $TAG
  
  docker-publish:
    if: github.ref == 'refs/heads/p2p-exercise' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: javiee
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build
        working-directory: ./p2p-app
        run: docker build -f docker/Dockerfile -t $DOCKER_IMAGE:${{ env.tag }} .

      - name: Push Docker image
        working-directory: ./p2p-app
        run: docker push $DOCKER_IMAGE:${{ env.tag }}

