name: Hello World

on:

  workflow_dispatch:
  push:
    branches:
      - p2p-exercise

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, World!"
