name: p2p app build

on:

  workflow_dispatch:
  push:
    branches:
      - p2p-exercise


env:
  GO_VERSION: 1.23.3
  PROJECT: p2p-app
  DOCKER_RESITORY: javiee/p
  DOCKER_IMAGE: your-dockerhub-username/go-app
  DOCKER_TAG: latest

jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        working-directory: ./p2p-devops-test
        run:  go build -o main .

      - name: Test with Go
        working-directory: ./p2p-devops-test
        run: go test -json > TestResults-${env.PROJECT}.json

      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${env.PROJECT}
          path: TestResults-${env.PROJECT}.json

